jobs:
  build38: &test-template
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            python -m pytest --cov croissant --cov-report xml
            bash <(curl -s https://codecov.io/bash) -t b7cffd27-ebe7-467e-ad67-cb600f258c4b
          name: Test

  build377:
    <<: *test-template
    executor:
      name: python/default
      tag: "3.7.7"

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install flake8
            # `|| true` to force exit code 0 even if no files found
            CHANGED_PYFILES=$(git diff --name-only --diff-filter AM origin/master | grep .py || true)
            echo "List of changed files:"
            echo ${CHANGED_PYFILES}
            echo ${CHANGED_PYFILES} | xargs -r flake8 --count
          name: Lint

orbs:
  python: circleci/python@0.3.2
version: 2.1
workflows:
  main:
    jobs:
      - build377
      - build38
      - lint
